spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gym_tracker
      auto-index-creation: true
logging:
  level:
    root: INFO
    com.edwise.batch: INFO
workout-config:
  fileNamePattern: "file:C:/Users/eanto/OneDrive/Documentos/personal-PC2023/gym/*.csv"