spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dev_gym_tracker
      auto-index-creation: true
logging:
  level:
    root: INFO
    com.edwise.batch: DEBUG
workout-config:
  fileNamePattern: "classpath:/workouts/*.csv"